language: python

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install python-coveralls

script: 
  py.test --cov-report= --cov=pynv tests
  
after_success:
  - coveralls
